.gitignore, package.json, packages/core/package.json
This small PR removes the unnecessary and potentially problematic fields from `package.json` files, fixes the [repository format](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository) in the main file and adds a IntelliJ IDEA project/cache directory to the `.gitignore`.
=> chore: cleanup package.json files, add IDEA related ignore

packages/core/styles/components/table-of-contents.css
Currently TOC styles uses `--ifm-toc-padding-vertical` variable to set both, vertical and horizontal values of `li` element margin. 
This PR fixes this issue and replaces the `-ifm-toc-padding-left` using newly added `-ifm-toc-padding-horizontal`.
The changes should not affect the styling in any way.
=> fix: do not use vertical var for both directions in TOC styling

packages/core/gulpfile.js, packages/core/package.json, yarn.lock
Adding generation of CSS bundle with styles for RTL direction. Thus, in Docusaurus core we will dynamically include the proper file (`default.css` or `default-rtl.css`), depending on the direction specified in the config file.
Of course, we can put CSS rulesets for RTL in one same default CSS file, but this will increase this file size, so it makes more sense to generate a separate bundle for this purpose.
=> feat: add RTL support

packages/core/demo/index.html, packages/core/styles/components/navbar.css
For improve accessibility purposes.
=> fix: use button instead of div for navbar toggle button

packages/core/styles/components/navbar.css
Attempts to make a smoother transition of the navbar sidebar display on mobiles. Based on the mobile Wikipedia website experience.
| ![ezgif com-gif-maker (15)](https://user-images.githubusercontent.com/4408379/107880909-ccad9100-6ef2-11eb-9046-6a3aa453d4c6.gif) | ![ezgif com-gif-maker (16)](https://user-images.githubusercontent.com/4408379/107880937-e64ed880-6ef2-11eb-83c4-7da2218a6992.gif) |
Builds:
- Before: https://infima63-before.netlify.app/
- After: https://infima63-after.netlify.app/
(Experiment) new changes with using `translate3d` instead of `translateX` for better graphics performance  https://infima63-after-translate3d.netlify.app/ 
cc @yangshun what do you think about this improvement (and also to replace `translateX` with …
=> refactor: improve UX of mobile navbar

packages/core/styles/components/navbar.css
=> fix: replace translateX by translate3d in mobile sidebar

.github/workflows/build-size.yml, package.json
We should be able to detect easily when the dist output is affected by a PR.
Asked by @Simek in https://github.com/facebookincubator/infima/pull/58#issuecomment-737512090
> Also as I was suggesting to @yangshun before, it might be nice to setup the dist CSS diff workflow on CI, so we can be sure that the output before and after the changes will be the same.
Is this way you had in mind or something more advanced?
=> chore: monitor dist size changes in PRs

.github/workflows/build-size.yml
The bot does not support "pull_request_target" apparently (which we need to post a PR comment on external contributors PRs)
https://github.com/preactjs/compressed-size-action/issues/54
Until it is fixed, we'll at least have the build size report for internal contributors 😅
=> chore: build-size-bot fix

.github/workflows/build-size.yml
`compression: 'none'` is an undocumented option but it's there
=> chore: build size bot: disable compression

netlify.toml, website/docusaurus.config.js
We want to deploy the infima Docusaurus site in deploy previews so that we can detect regressions for a Docusaurus site using the classic theme.
Also deploys the existing HTML demo, but we'd rather migrate it as a standalone page of the site?
=> chore: Update Netlify to publish site + demo

package.json, yarn.lock
As seen in Docusuaurs 2 repo (https://github.com/facebook/docusaurus/pull/3738), besides initial concerns, adding [`npx yarn-deduplicate`](https://github.com/atlassian/yarn-deduplicate) isn't a bad idea and can be used as a long term solution for keeping `yarn.lock` tidy.
This PR adds the deduplication script to the `postinstall` of the workspace and includes the changes added by running the script.
CC @slorber
=> chore: add yarn-deduplicate to the postinstall, clean lock

.github/workflows/build-size.yml, yarn.lock
After investigating a security issue using `pull_request_target`, we decided to finally keep build size bot but using `pull_request`.
It solves the security issue, but this means the build size bot won't be able to post a PR comment if the PR is from a fork.
See https://github.com/preactjs/compressed-size-action/issues/54
See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
=> misc: restore build size bot

packages/core/package.json, packages/postcss-preset-infima/package.json, website/package.json, yarn.lock
This PR bumps the Docusaurus used for website to the latest alpha release (`alpha.71`).
It also includes the Infima version align in the packages dependencies, not included in #94. 
The new release might be required, since `alpha.20` release do not ensure that all users would update to new `postcss-preset-infima` version automatically.
=> chore: bump Docusaurus, align Infima version

PUBLISH.md
Update publish guide, to minimize the risk of misaligned dependencies in the future.
Refs #94, #95
=> chore: update publish guide

PUBLISH.md
Refs #98 
Add one more step to ensure that lockfile is regenerated properly after the packages version bump.
=> chore: update publishing guide again

packages/core/styles/content/heading.pcss
Root variable was created but never actually assigned to the headers.
=> fix: apply --ifm-heading-font-family to headings

packages/core/dist/css/default-dark/default-dark-rtl.css, packages/core/dist/css/default-dark/default-dark.css, packages/core/dist/css/default/default-rtl.css, packages/core/dist/css/default/default.css, packages/core/styles/components/button.pcss
Currently, due to unusual placement of comments for button styles, there are line breaks around `var` function that will appear in the final CSS bundle (even minimizer do not remove them).
However, if we change comments position, this issue will be resolved.
=> fix: move position of comments to better minification

README.md
Currently used link leads to the broken page:
=> chore: use correct website URL in Readme

README.md, packages/core/demo/index.html, packages/core/styles/common/dark-mode.pcss, packages/core/styles/common/variables-dark.pcss, packages/core/styles/common/variables.pcss, packages/core/styles/components/alert.pcss, packages/core/styles/components/tabs.pcss, packages/core/styles/content/code.pcss, packages/core/styles/content/typography.pcss, website/docs/components/alert.mdx, website/package.json, yarn.lock
Fix https://github.com/facebookincubator/infima/issues/55
Redesign Infima alerts so that we can redesign Docusaurus admonitions:
- Reuse existing Infima colors
- Add new color variants `--ifm-color-$(color)-contrast background + `--ifm-color-$(color)-contrast-emphasis`
- Emphasis on background pass WCAG contrast tests with AAA
- Keep dark mode support
- Make it easy to customize alerts/admonitions through CSS variables
- Also redesign blockquotes to be consistent with alert design (and fix highly inaccessible contrast)
- Support for tabs
Not directly related:
- Simplify existing verbose color declaration with `@each`
- Apply missing `.clean-btn` class on Alert doc page, issue appearing after #150
- Add anchor links to Infima demo sections
- Alerts: …
=> Alert / Admonition redesign

packages/core/demo/index.html, packages/core/styles/common/dark-mode.pcss, packages/core/styles/common/variables-dark.pcss, packages/core/styles/common/variables.pcss, packages/core/styles/components/alert.pcss, packages/core/styles/content/heading.pcss, packages/core/styles/content/typography.pcss
Currently, blockquotes are very similar to secondary alerts, so it would be good to make them more different in styling.
Similar to v1, we can take light yellow color as background, then current content color (black/white depending on color mode) and also remove border-radius (unlike in alerts). We'll end up with something like this:
| ![image](https://user-images.githubusercontent.com/4408379/126893214-452a24c5-ea95-45f8-8beb-ceb494dba805.png) | ![image](https://user-images.githubusercontent.com/4408379/126893222-9dadd37a-bc49-4bee-99f9-126431cfc0d8.png) |
Beside this, as part of this PR, emphasis word is renamed to "foreground"  (for better clarity), and removing increase of text decoration line at focus state, because it does not make …
=> refactor: new blockquotes styling + minor tweaks

packages/core/demo/index.html, packages/core/styles/common/base.pcss
Report fix of @lex111 in Infima: https://github.com/facebook/docusaurus/pull/5223
The behavior of color-scheme for iframes look a bit weird. Without "auto" it seems to apply the value of the parent at the moment the iframe loads (leading to potentially a bad iframe background), and then does not update on parent color-scheme changes. Auto seems to "track" better the color-scheme changes of the parent.
=> Fix iframe color-scheme CSS

packages/core/styles/common/base.pcss
Let's remove default browser useless border in iframes. For example, Bootstrap and many other CSS frameworks removes iframe border by default.
=> refactor: remove default border in iframes

packages/core/demo/index.html, packages/core/styles/components/navbar.pcss
Because in Docusaurus we need to display secondary menu even when there is no main one, we have to remove back button to main menu. This PR paves the way to this, setting proper padding when there is no back button:
| ![image](https://user-images.githubusercontent.com/4408379/127515835-951e500c-9543-4764-b3a2-dd2760c88da9.png) | ![image](https://user-images.githubusercontent.com/4408379/127515678-5c28bb7a-9c5a-4fcf-a922-cea572329b38.png) |
=> refactor: make optional sidebar back button

packages/core/styles/components/dropdown.pcss, packages/core/styles/components/navbar.pcss
First of all Docusaurus currently uses not entirely correct markup for dropdown navbar item, because `navbar__item` class is used for link inside:
However on demo page shows that `navbar__item` class should be on parent element only:
It follows that `navbar__link` class should not add padding, since `navbar__item` class is designed to do this. That's why we now have this small duplication of code:
Also, we don't have to remove padding from dropdown navbar item because we can simply adjust `top` position.
=> refactor: minor navbar/dropdown cleanup

packages/core/styles/content/markdown.pcss
Related with https://github.com/facebook/docusaurus/discussions/5356
Because in Docusaurus `h1` element of doc page is nested inside `header` element, we have to add (other words, = duplicate) styles for h1 in [separate class](https://github.com/facebook/docusaurus/blob/57806798c5c13ddf20f9f654141e9617ad06a1ee/packages/docusaurus-theme-classic/src/theme/Heading/styles.module.css#L12-L15). I suppose we can avoid that by making these small edits in Infima. 
- Since in most cases the first element on doc page (inside `markdown` class) will be h1, we don't need to set top margin for it (and therefore reset its top margin for this element later).
- We also assume now that there will only be one h1 in doc content area, I think in most of Docusaurus websites this change won't break anything …
=> refactor: h1 margin-top adjustments

packages/core/demo/index.html, packages/core/styles/common/dark-mode.pcss, packages/core/styles/content/typography.pcss
Fix https://github.com/facebook/docusaurus/issues/5244
Yellow blockquotes are not something people like/expect, and despite a few users liking this design, we should move to something soberer and more widely accepted.
Revert to what we had before the admonitions changes, but with more accessible colors and less vertical spacing, similar to what many other sites/fwk are doing.
=> refactor: redesign blockquotes to more common design

.github/workflows/build-size.yml, .github/workflows/lint.yml, .github/workflows/post-diff-comment.yml, CONTRIBUTING.md, PUBLISH.md, README.md
The OSS team has changed all `master` branches to `main` for most FB repos and we need to update and references to `master` in our code.
Do we need to change anything on Netlify side?
CI should pass.
=> chore: change CI branch from master to main

packages/core/demo/index.html, packages/core/styles/components/navbar.pcss
=> refactor: align mobile sidebar close button to right side

packages/core/styles/utilities/custom-scrollbar.pcss
Before in firefox:
After chrome/firefox:
=> Add support for thin scrollbars on firefox

packages/core/demo/index.html, packages/core/styles/components/menu.pcss
Should resolve #188 
Not the ideal option (and probably not final design), but so far I can't imagine how it should look like. Definitely need to support two versions -- with pseudo element in case of categories without index page (as it was before), and with new use case, when text and icon are represented as separate elements.
Technically, for menu item with category index need to add a new `<button>` element after the link element. In the case of a "regular" category, everything is unchanged (only the `menu__link--sublist` class on menu link is required).
=> feat: embed icon of collapsible item as separated element

packages/core/demo/index.html, packages/core/styles/components/pagination-nav.pcss, website/docs/components/pagination-nav.mdx
**This issue stems from:** https://github.com/facebook/docusaurus/pull/6053
Short summary:
I'd like to stylize the `pagination-nav` so it looks like this:
The problem is that the arrows `»` are just inlined into the markup and cannot be hidden via CSS:
This is why I move them to `::before` and `::after` pseudo-elements, so that later on I am able to hide them completely and continue my styling described above.
=> feat: make pagination-nav arrows stylizable

packages/core/styles/components/menu.pcss
Fixes #198 
As described in the linked issue, using the `background` CSS property to set only the `background-color` makes it more difficult to set other individual `background-*` properties downstream, since they get clobbered unless the selector chain is specific enough.
As a rule, it would be better to use the `background-color` property specifically when that is all that is being set. Per @lex111's advice, this MR only updates the example I am having problems with.
Note that this does not completely resolve the linked issue, but it does resolve _my_ particular use case.
Since this is my first PR to the project, please let me know if there are additional changes I should make!
=> fix: prefer background-color property (#198)

packages/core/demo/index.html, packages/core/styles/components/menu.pcss
The positioning of a caret down icon of menu item  to the right should not affect other elements, in particular a external icon.
=> refactor: better positioning of menu item icon

packages/core/styles/content/table.pcss
I think table header looks better with more emphasized background (especially because the first tbody row is less emphasized). Intended result: 
Before | After
------ | -----
=> refactor: more emphasized background color for table header

packages/postcss-preset-infima/index.js, packages/postcss-preset-infima/package.json, yarn.lock
This makes things work at bare minimum.
cc @rdil @slorber We may need to eventually remove `color-mod` and hardcode color values until the spec is updated.
Related #211 #212
=> chore: upgrade postcss-preset-env to v7

packages/core/styles/components/table-of-contents.pcss
Just expanding the clickable area of a link is good for UX.
=> refactor: make TOC link clickable over full width

packages/core/demo/index.html, packages/core/styles/components/menu.pcss
We should apply consistently the `menu__link--sublist` on category items (with/without link) otherwise it breaks search feature on all sites that are using category links
Introduce a new `menu__link--sublist-caret` class to add back the caret feature only when the class is added (otherwise it shows duplicate caret: button + CSS)
---
We'll find a way to create stable selectors for the crawler, but for now it's simpler to be retro compatible with all the existing search configs and ensure the current Algolia crawler selector keeps working
```js
const lvl0 =
$(
".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active"
)
.last()
.text() || "Documentation";
return helpers.docsearch({
recordProps: {
lvl0: {
selectors: "",
defaultValue: lvl0,
},
lvl1: "header h1", …
```
=> fix: apply menu__link--sublist consistently to fix Docusaurus search issue

packages/core/styles/content/typography.pcss
Now the sizing for `<hr>` element is confusing: although it is set as 1px by default, but it is actually 2px because the top and bottom borders are summed.
=> fix: proper sizing for hr element

packages/core/styles/content/markdown.pcss
Following my PR on Docusaurus: https://github.com/facebook/docusaurus/pull/7004#issuecomment-1081214521
The goal here is to fix the size of titles on mobile (too big right now).
I'm not 100% sure of this PR, I'm not an expert in .pcss. 
How could I test this PR on the docusaurus repo ?
=> Markdown: Adapt font-size on mobile

packages/core/demo/index.html, packages/core/styles/components/menu.pcss
Since soon it will be possible to place pure HTML markup, including SVG icons, inside the navbar items, they will now be mis-positioned in the mobile sidebar.
| ![image](https://user-images.githubusercontent.com/4408379/161260612-6911c3ee-7f35-4e35-87ee-24e3ea687036.png) | ![image](https://user-images.githubusercontent.com/4408379/161260892-8b0adc3e-e397-403d-adf3-d4831270e038.png) |
=> refactor: better positioning of caret icon in menu item

.github/workflows/post-diff-comment.yml
I realized that whitespace changes (e.g. indentation) often obscure actual code changes. Similar to how GitHub has the "hide whitespace" option, we can also ignore whitespace when generating diff.
=> chore: ignore whitespace when diffing css

packages/core/styles/components/breadcrumb.pcss
Currently the spacing of breadcrumbs seems rather large, I suggest making them more compact.
| ![image](https://user-images.githubusercontent.com/4408379/163334980-9a65886a-7ac8-4b09-a610-bccf496221e2.png) | ![image](https://user-images.githubusercontent.com/4408379/163334881-a2dd7dcf-03ef-4d05-a0ce-b0bf195bf540.png) |
=> refactor: make breadcrumbs tighter

packages/core/styles/components/breadcrumb.pcss
The hover state of breadcrumb item should not be triggered when hovering over breadcrumb separator.
=> refactor: apply hover state on breadcrumb link only

packages/core/styles/components/tabs.pcss
This tiny margin only applies on mobiles and only for full-width tabs, so it's not really clear why it's needed, so let's remove it.
=> refactor: remove useless spacing for tabs

packages/core/demo/index.html, packages/core/styles/common/dark-mode.pcss, packages/core/styles/content/code.pcss
Related to #199
After doing a little studying of dark mode sites, I've come to the conclusion that it's really worth using less contrast for base content color if dark mode is on:
| Site             | Contrast ratio (dark mode)
| ------------- | ---
| [docs.microsoft.com](https://docs.microsoft.com/en-us/azure/architecture/changelog) | [14.36 ](https://webaim.org/resources/contrastchecker/?fcolor=E6E6E6&bcolor=171717 ) |
| [developers.cloudflare.com](https://developers.cloudflare.com/workers/get-started/guide/) | [11.45](https://webaim.org/resources/contrastchecker/?fcolor=D5D7D8&bcolor=1D1F20) |
| [Mk Docs Material](https://webaim.org/resources/contrastchecker/?fcolor=E9EBFC&bcolor=2E303E) | [11.03](https://webaim.org/resources/contrastchecker/?fcolor=E9EBFC&bcolor=2E303E) |
| …
=> refactor: make some dark mode colors less contrast

packages/core/styles/components/menu.pcss
As a rule, the horizontal spacing should not be more than twice that of the vertical one (eg, this is true for dropdown items).
=> refactor: normalize menu link horizontal spacing

packages/core/demo/index.html, packages/core/styles/components/pagination-nav.pcss
- Less code
- Simpler markup
- No need for adding an empty element if there is no next/prev link
=> refactor: use grid layout for pagination nav

packages/core/styles/components/button.pcss
Trying a modern way to solve the specificity issue to reduce the final CSS bundle size.
=> refactor: remove code duplication in buttons styles

website/docs/components/footer.mdx
Fixes https://github.com/facebookincubator/infima/issues/239
Note there's still one case where we display the logo for dark mode on a light background:
I think it's better to not fix it because the documented markup is static (but the theme/backgroundColor is dynamic): fixing this would likely create noise in our doc for little ROI
=> Fix broken footer logo in Infima Footer doc

packages/core/demo/index.html, packages/core/styles/components/breadcrumb.pcss, packages/core/styles/content/typography.pcss
Breadcrumb items do not necessarily have an `href`, but they always change color when the user hovers over them. The hover styles give the impression that the breadcrumb item is a clickable link even if this is not the case.
This can be seen in the [Redux documentation](https://redux.js.org/tutorials/essentials/part-1-overview-concepts) — neither "Tutorials" nor "Redux Essentials" are links, yet they have hover styles.
This PR uses the `:link` pseudoselector to fix this.
Edit: Signed the CLA.
=> fix: breadcrumb links without `href` should not have hover styles

packages/core/demo/index.html, packages/core/styles/content/typography.pcss
Revert half of https://github.com/facebookincubator/infima/pull/266
`a:any-link:hover` change is not necessary and was based on an artificial usage of `<a className="xyz">` which we don't have in practice (we use `<span>` in such cases)
---
<details>
<summary>Former issue text before reverting</summary>
Fix issue where all links have unexpected underlines:
Docusaurus issue: https://github.com/facebook/docusaurus/issues/7748
See comment https://github.com/facebookincubator/infima/pull/266/files#r917208453
Alternative PR: https://github.com/facebookincubator/infima/pull/267
Support for `:where` is good enough and we already use it anyway: https://caniuse.com/?search=where
It's a good new tool to keep CSS specificity low
</details>
=> fix: revert useless a:any-link:hover change

packages/core/styles/components/navbar.pcss
closes #306 
This is because inputs should have a minimum font size of 16px, anything lower will cause a zoom in on iOS.
https://stackoverflow.com/a/6394497/11334432
before:
https://github.com/facebookincubator/infima/assets/34947993/1f520e46-d993-423c-b99d-d7d6c89b9418
after:
https://github.com/facebookincubator/infima/assets/34947993/e5124b37-c72e-4bd2-aa54-77f26e81e23c
=> fix: navbar search input zoom on focus

package.json
Define the package manager version in the package.json to ensure consistency across installations.
=> Specify package manager version in package.json
