facebookincubator/infima

- website/docusaurus.config.js
this PR add link to redirect open source fb website!.
> misc: add link to redirect open source website

- packages/core/package.json
- packages/core/styles/components/navbar.css
- packages/postcss-preset-infima/index.js
- packages/postcss-preset-infima/package.json
- yarn.lock
Some fixes for development process based on the review by @Simek, and also use to more appropriate value to clear of button background.
> refactor: various clean-ups and fixes

- website/docusaurus.config.js
> website: add legal links

- README.md
- website/src/pages/index.js
v1-v2 Docusaurus domains have been interverted and v2 is the main doc now
> docs: domain switch

- website/docs/layout/spacing.mdx
Related issue: #105 
The docs are quite similar to the bootstrap ones as the implementation is mostly the same.
> docs: add spacing docs

- .github/workflows/build-size.yml
- package.json
> chore: fix buildsize ci

- packages/core/styles/components/button.pcss
- packages/core/styles/components/menu.pcss
- packages/core/styles/components/navbar.pcss
- packages/core/styles/content/image.pcss
- packages/core/styles/content/table.pcss
- packages/core/styles/content/typography.pcss
A follow-up of #150
Basically, this is superfluous code that can be safely removed.
> refactor: remove excess styles

- packages/core/styles/utilities/misc.pcss
> fix: use standard font-family in cleaned buttons

- packages/core/styles/components/footer.pcss
- packages/core/styles/components/menu.pcss
- packages/core/styles/components/table-of-contents.pcss
Purely for simplicity and micro-optimization
> refactor: use shorthand property to reset list

- packages/core/demo/index.html
- packages/core/styles/components/navbar.pcss
Based on https://github.com/facebookincubator/infima/pull/161#issuecomment-908213009
> feat: add close mobile navbar button

- packages/core/demo/index.html
- packages/core/js/menu.js
- packages/core/styles/components/menu.pcss
- packages/postcss-preset-infima/index.js
Follow-up of #190 (see https://github.com/facebookincubator/infima/pull/190#issuecomment-983824427)
> refactor: improve active/hover state for caret button

- packages/core/demo/index.html
- packages/core/styles/common/dark-mode.pcss
- packages/core/styles/content/table.pcss
Fixes #195
@Josh-Cena take a look please.
> refactor: use semi-transparent background for striped rows

- website/README.md
Add readme file in the website directory with instructions to server locally for testing/development.
> website: add readme

- .github/workflows/lint.yml
- .husky/pre-commit
- .lintstagedrc.json
- .stylelintrc.js
- package.json
- packages/core/package.json
- yarn.lock
Deduplicated some packages, moved all lint commands to the root.
> chore: refactor dev setup

- .github/workflows/post-diff-comment.yml
Hope this would do something... Installing after building seems like a terrible idea to me
> chore: fix CSS diff action when upgrading deps

- package.json
- packages/core/package.json
- packages/postcss-preset-infima/package.json
- yarn.lock
Some trivial ones. Harder ones from #211 are not touched (yet).
> chore: upgrade dependencies

- .stylelintrc.js
- package.json
- yarn.lock
> chore: upgrade stylelint-copyright

- packages/core/demo/index.html
- packages/core/styles/components/dropdown.pcss
Should fix https://github.com/facebook/docusaurus/issues/7046
> fix: fix flickering dropdown on hover over its corner

- packages/core/demo/index.html
- packages/core/styles/components/avatar.pcss
Currently the avatar markup seems a bit verbose, as do the styles (duplicate height/width for each sizing), so let's fix it. Visible result will be same as before.
> refactor: improve avatar markup/styles

- packages/core/styles/components/pills.pcss
A much better approach that also takes less code.
> refactor: use flex for pills spacing

- packages/core/demo/index.html
- packages/core/styles/common/base.pcss
- packages/core/styles/components/alert.pcss
- packages/core/styles/components/button.pcss
- packages/core/styles/components/menu.pcss
- packages/core/styles/components/navbar.pcss
- packages/core/styles/components/pagination.pcss
- packages/core/styles/content/markdown.pcss
- packages/core/styles/content/table.pcss
- packages/core/styles/content/typography.pcss
> refactor: minor optimizations

- packages/core/styles/components/pagination.pcss
Just a small optimization to simplify the code.
> refactor: use flex layout for pagination

- packages/core/styles/layout/grid.pcss
> refactor: reduce CSS specificity for grid rules

- packages/core/styles/layout/grid.pcss
> refactor: make column classes standalone

- packages/core/styles/components/dropdown.pcss
Fix https://github.com/facebook/docusaurus/issues/7330
> fix: adjust dropdown position for Safari

- package.json
Little maintainer annoyance, see also https://github.com/facebook/docusaurus/pull/7549
> npx --yes yarn-deduplicate
